### ISSUE TITLE
Create sample yaml file

### ISSUE THREAD

**Issue by nmls** [LaatuGroup/flink#1]
First step would be creating a sample yaml file that would basic VM settings such as:
- os (image + information on how to build the image); right now only centos7;
- cpu;
- memory;
- networking;
- hostname;
- bootstraping inline.

**Comment by nmls** [comment]
````
vms:
  myvm:
    name: My Virtual Machine
    image: centos:7
    provider: vbox
    root_password: password123
    hardware:
      cpus: 1
      memory: 512
    networks:
      - type: nat
      - type: host-only
        ip_address: 192.168.56.110
    hostname: myvm.laatu.internal
    bootstrap:
      - shell: "echo 'Hello' > /etc/motd"

````
